report_header_info:
    - Analysis by:: 'Malwina Prater'
    - Contact E-mail:: 'xxx@xxx.ac.uk'
    - Application Type:: 'scRNA-seq + scATAC-seq'
    - Project Type:: '10x multiOme'
    - Project Owners:: 'collaborator1 & collaborator2'
    - Sequencing Platform:: 'Illumina '
    - Sequencing Setup:: 'standard'

title: "Project ID ::: MBU_groupId_ProjID"
subtitle: "Mitochondrial biology Unit, MRC, University of Cambridge"
intro_text: "Pipeline created by Malwina Prater, MBU Bioinformatics"

#output_fn_name: MBU_groupId_ProjID.multiqc_report.html
#data_dir_name: MBU_groupId_ProjID.multiqc_data

fn_ignore_files:
    - '*lostreads*'
fn_ignore_dirs:
    - 'work'
    - 'SC_ATAC_GEX_COUNTER_CS'
fn_ignore_paths:
    - 'count/*/*outs/SC_ATAC_GEX_COUNTER_CS/*'


custom_logo: '/suffolk/WorkGenomicsE/mn367/Logo/LOGO_MRC_MBU_Cambridge_RGB.png'
custom_logo_url: 'http://www.mrc-mbu.cam.ac.uk/'
custom_logo_title: 'MRC Mitochondrial Biology Unit, University of Cambridge'
